package enity;
// Generated 2017/7/17 �U�� 04:20:09 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NursesId generated by hbm2java
 */
@Embeddable
public class NursesId implements java.io.Serializable {

	private String employeeNo;
	private String nursesName;
	private Date updateTime;

	public NursesId() {
	}

	public NursesId(String employeeNo, String nursesName, Date updateTime) {
		this.employeeNo = employeeNo;
		this.nursesName = nursesName;
		this.updateTime = updateTime;
	}

	@Column(name = "Employee_no", nullable = false, length = 50)
	public String getEmployeeNo() {
		return this.employeeNo;
	}

	public void setEmployeeNo(String employeeNo) {
		this.employeeNo = employeeNo;
	}

	@Column(name = "Nurses_name", nullable = false, length = 50)
	public String getNursesName() {
		return this.nursesName;
	}

	public void setNursesName(String nursesName) {
		this.nursesName = nursesName;
	}

	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NursesId))
			return false;
		NursesId castOther = (NursesId) other;

		return ((this.getEmployeeNo() == castOther.getEmployeeNo()) || (this.getEmployeeNo() != null
				&& castOther.getEmployeeNo() != null && this.getEmployeeNo().equals(castOther.getEmployeeNo())))
				&& ((this.getNursesName() == castOther.getNursesName()) || (this.getNursesName() != null
						&& castOther.getNursesName() != null && this.getNursesName().equals(castOther.getNursesName())))
				&& ((this.getUpdateTime() == castOther.getUpdateTime())
						|| (this.getUpdateTime() != null && castOther.getUpdateTime() != null
								&& this.getUpdateTime().equals(castOther.getUpdateTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEmployeeNo() == null ? 0 : this.getEmployeeNo().hashCode());
		result = 37 * result + (getNursesName() == null ? 0 : this.getNursesName().hashCode());
		result = 37 * result + (getUpdateTime() == null ? 0 : this.getUpdateTime().hashCode());
		return result;
	}

}
