package enity;
// Generated 2017/7/17 �U�� 04:20:09 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Station generated by hbm2java
 */
@Entity
@Table(name = "station", catalog = "bionime")
public class Station implements java.io.Serializable {

	private Integer stationNo;
	private String stationName;
	private Date updateTime;

	public Station() {
	}

	public Station(String stationName, Date updateTime) {
		this.stationName = stationName;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "station_no", unique = true, nullable = false)
	public Integer getStationNo() {
		return this.stationNo;
	}

	public void setStationNo(Integer stationNo) {
		this.stationNo = stationNo;
	}

	@Column(name = "station_name", length = 50)
	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
