package bionime.enity;
// Generated 2017/7/15 �U�� 03:39:19 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Nurses generated by hbm2java
 */
@Entity
@Table(name = "nurses", catalog = "bionime")
public class Nurses implements java.io.Serializable {

	private NursesId id;

	public Nurses() {
	}

	public Nurses(NursesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "employeeNo", column = @Column(name = "Employee_no", length = 50)),
			@AttributeOverride(name = "nursesName", column = @Column(name = "Nurses_name", length = 50)) })
	public NursesId getId() {
		return this.id;
	}

	public void setId(NursesId id) {
		this.id = id;
	}

}
