package bionime.enity;
// Generated 2017/7/15 �U�� 03:39:19 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NursesId generated by hbm2java
 */
@Embeddable
public class NursesId implements java.io.Serializable {

	private String employeeNo;
	private String nursesName;

	public NursesId() {
	}

	public NursesId(String employeeNo, String nursesName) {
		this.employeeNo = employeeNo;
		this.nursesName = nursesName;
	}

	@Column(name = "Employee_no", length = 50)
	public String getEmployeeNo() {
		return this.employeeNo;
	}

	public void setEmployeeNo(String employeeNo) {
		this.employeeNo = employeeNo;
	}

	@Column(name = "Nurses_name", length = 50)
	public String getNursesName() {
		return this.nursesName;
	}

	public void setNursesName(String nursesName) {
		this.nursesName = nursesName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NursesId))
			return false;
		NursesId castOther = (NursesId) other;

		return ((this.getEmployeeNo() == castOther.getEmployeeNo()) || (this.getEmployeeNo() != null
				&& castOther.getEmployeeNo() != null && this.getEmployeeNo().equals(castOther.getEmployeeNo())))
				&& ((this.getNursesName() == castOther.getNursesName())
						|| (this.getNursesName() != null && castOther.getNursesName() != null
								&& this.getNursesName().equals(castOther.getNursesName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEmployeeNo() == null ? 0 : this.getEmployeeNo().hashCode());
		result = 37 * result + (getNursesName() == null ? 0 : this.getNursesName().hashCode());
		return result;
	}

}
