package bionime.enity;
// Generated 2017/7/16 �W�� 09:32:48 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Stationdetail generated by hbm2java
 */
@Entity
@Table(name = "stationdetail", catalog = "bionime")
public class Stationdetail implements java.io.Serializable {

	private StationdetailId id;

	public Stationdetail() {
	}

	public Stationdetail(StationdetailId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "stationNo", column = @Column(name = "station_no")),
			@AttributeOverride(name = "employeeNo", column = @Column(name = "employee_no", length = 50)),
			@AttributeOverride(name = "updateTime", column = @Column(name = "update_time", length = 19)) })
	public StationdetailId getId() {
		return this.id;
	}

	public void setId(StationdetailId id) {
		this.id = id;
	}

}
