package bionime.enity;
// Generated 2017/7/16 �W�� 09:32:48 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StationdetailId generated by hbm2java
 */
@Embeddable
public class StationdetailId implements java.io.Serializable {

	private Integer stationNo;
	private String employeeNo;
	private Date updateTime;

	public StationdetailId() {
	}

	public StationdetailId(Integer stationNo, String employeeNo, Date updateTime) {
		this.stationNo = stationNo;
		this.employeeNo = employeeNo;
		this.updateTime = updateTime;
	}

	@Column(name = "station_no")
	public Integer getStationNo() {
		return this.stationNo;
	}

	public void setStationNo(Integer stationNo) {
		this.stationNo = stationNo;
	}

	@Column(name = "employee_no", length = 50)
	public String getEmployeeNo() {
		return this.employeeNo;
	}

	public void setEmployeeNo(String employeeNo) {
		this.employeeNo = employeeNo;
	}

	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StationdetailId))
			return false;
		StationdetailId castOther = (StationdetailId) other;

		return ((this.getStationNo() == castOther.getStationNo()) || (this.getStationNo() != null
				&& castOther.getStationNo() != null && this.getStationNo().equals(castOther.getStationNo())))
				&& ((this.getEmployeeNo() == castOther.getEmployeeNo()) || (this.getEmployeeNo() != null
						&& castOther.getEmployeeNo() != null && this.getEmployeeNo().equals(castOther.getEmployeeNo())))
				&& ((this.getUpdateTime() == castOther.getUpdateTime())
						|| (this.getUpdateTime() != null && castOther.getUpdateTime() != null
								&& this.getUpdateTime().equals(castOther.getUpdateTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStationNo() == null ? 0 : this.getStationNo().hashCode());
		result = 37 * result + (getEmployeeNo() == null ? 0 : this.getEmployeeNo().hashCode());
		result = 37 * result + (getUpdateTime() == null ? 0 : this.getUpdateTime().hashCode());
		return result;
	}

}
