package bionime.enity;
// Generated 2017/7/15 �U�� 03:39:19 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Station generated by hbm2java
 */
@Entity
@Table(name = "station", catalog = "bionime")
public class Station implements java.io.Serializable {

	private Integer stationNo;
	private String stationName;

	public Station() {
	}

	public Station(String stationName) {
		this.stationName = stationName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "station_no", unique = true, nullable = false)
	public Integer getStationNo() {
		return this.stationNo;
	}

	public void setStationNo(Integer stationNo) {
		this.stationNo = stationNo;
	}

	@Column(name = "station_name", length = 50)
	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

}
