package bionime.enity;
// Generated 2017/7/15 �U�� 03:39:19 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StationdetailId generated by hbm2java
 */
@Embeddable
public class StationdetailId implements java.io.Serializable {

	private Integer stationNo;
	private String employeeNo;

	public StationdetailId() {
	}

	public StationdetailId(Integer stationNo, String employeeNo) {
		this.stationNo = stationNo;
		this.employeeNo = employeeNo;
	}

	@Column(name = "station_no")
	public Integer getStationNo() {
		return this.stationNo;
	}

	public void setStationNo(Integer stationNo) {
		this.stationNo = stationNo;
	}

	@Column(name = "employee_no", length = 50)
	public String getEmployeeNo() {
		return this.employeeNo;
	}

	public void setEmployeeNo(String employeeNo) {
		this.employeeNo = employeeNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StationdetailId))
			return false;
		StationdetailId castOther = (StationdetailId) other;

		return ((this.getStationNo() == castOther.getStationNo()) || (this.getStationNo() != null
				&& castOther.getStationNo() != null && this.getStationNo().equals(castOther.getStationNo())))
				&& ((this.getEmployeeNo() == castOther.getEmployeeNo())
						|| (this.getEmployeeNo() != null && castOther.getEmployeeNo() != null
								&& this.getEmployeeNo().equals(castOther.getEmployeeNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStationNo() == null ? 0 : this.getStationNo().hashCode());
		result = 37 * result + (getEmployeeNo() == null ? 0 : this.getEmployeeNo().hashCode());
		return result;
	}

}
